gsap-generate.sh

diff --git a/gsoap/soap-generate-sh b/gsoap/soap-generate-sh
--- a/gsoap/soap-generate-sh
+++ b/gsoap/soap-generate-sh
@@ -19,7 +19,7 @@ print-usage() {
     echo "<wsdl infile or url> is wsdl file or url to read."
     echo "Options:"
     echo -e "-h, --help\t\tPrint this help."
-    echo -e "-o, --output <path>\t\tUse <path> as output folder."
+    echo -e "-o, --output <path>\tUse <path> as output folder."
 }
 
 function generate-class() {
@@ -66,7 +66,7 @@ function generate-class() {
     #    echo -e "\e[33m$value\e[0m"
     #done
     
-    # Print each value of the array by using loop
+    # Create all
     for (( n=0; n < ${#reqNamespaceArray[*]}; n++)); do
         # retain the part after $wsdlName
         function=${reqNamespaceArray[n]##*$wsdlName}
@@ -79,10 +79,13 @@ function generate-class() {
             create_if_not_exists $outputFolder/$className
         fi
         #To replace all occurrences, use ${parameter//pattern/string}:
-        echo -e "Generating \e[33m$className.h\e[33m\e[0m"
+        echo -e "Generating \e[33m$className.h\e[0m"
         sed "s/<classNamespace>/$classNamespace/g; s/<className>/$className/g; s/<functionName>/$functionName/g; s/<serviceNamespace>/$serviceNamespace/g; s/<reqNamespace>/${reqNamespaceArray[n]}/g; s/<resNamespace>/${resNamespaceArray[n]}/g" $templatesFolder/$DSOAP_H_TEMPLATE > $outputFolder/$className/$className.h
-        echo -e "Generating \e[33m$className.cpp\e[33m\e[0m"
-        sed "s/<classNamespace>/$classNamespace/g; s/<className>/$className/g; s/<functionName>/$functionName/g; s/<serviceNamespace>/$serviceNamespace/g; s/<reqNamespace>/${reqNamespaceArray[n]}/g; s/<resNamespace>/${resNamespaceArray[n]}/g" $templatesFolder/$DSOAP_CPP_TEMPLATE > $outputFolder/$className/$className.cpp
+        echo -e "Generating \e[33m$className.cpp\e[0m"
+        sed "s/<classNamespace>/$classNamespace/g; s/<className>/$className/g; s/<functionName>/$functionName/g; s/<serviceNamespace>/$serviceNamespace/g; s/<reqNamespace>/${reqNamespaceArray[n]}/g; s/<resNamespace>/${resNamespaceArray[n]}/g;" $templatesFolder/$DSOAP_CPP_TEMPLATE > $outputFolder/$className/$className.cpp
+		# Replace also <wsdlUrl> with wsdl source $wsdlUrl
+		gawk -i inplace -v wsdlUrl=$wsdlUrl '{gsub(/<wsdlUrl>/,wsdlUrl)}1' $outputFolder/$className/$className.cpp
+		echo -e "Generating \e[33m$"CMakeLists.txt"\e[0m"
         sed "s/<classNamespace>/$classNamespace/g; s/<functionName>/$functionName/g; s/<serviceNamespace>/$serviceNamespace/g; s/<reqNamespace>/${reqNamespaceArray[n]}/g; s/<resNamespace>/${resNamespaceArray[n]}/g" $templatesFolder/$CMAKELISTS_TXT_TEMPLATE > $outputFolder/$className/CMakeLists.txt
         echo -e "Adding lib files to \e[33m$className\e[0m folder"
         cp $tempFolder/{soapC.cpp,soapH.h,soapStub.h,$serviceNamespace.nsmap,soap"$serviceNamespace"Proxy.cpp,soap"$serviceNamespace"Proxy.h} $templatesFolder/stdsoap2.cpp $templatesFolder/stdsoap2.h $outputFolder/$className
@@ -125,38 +128,67 @@ done
 set -- "${POSITIONAL[@]}" # restore positional parameters
         
 if [[ $# < 2 ]]; then
-    echo "Missing arguments..."
+    echo -e "\e[1;41mError: missing arguments...\e[0m"
     print-usage
     exit
 fi
 
-# output, templates and temp folder
+# Output folder
 if [[ ${outputFolder} == "" ]]; then
     outputFolder=$(pwd)
 fi
+
+# Templates folder
 if [[ ${templatesFolder} == "" ]]; then
-    templatesFolder=$(pwd)/templates
+    templatesFolder=$(printenv DDEV_GSOAP_TEMPLATES)
 fi
+if [[ ! -d $templatesFolder ]]; then
+	echo -e "\e[1;41mError: template folder not set. Use -t to specifiy folder or set DDEV_GSOAP_TEMPLATES environment variable to folder.\e[0m"
+	exit
+fi
+
+# Temp folder
 tempFolder=$(pwd)/temp
     
 
 echo "-- $(basename "$0") Ver. $Version --"
-
-# Generate gsoap files
-echo -e "Executing \e[33mwsdl2h\e[0m"
 create_if_not_exists $tempFolder
+
+# wsdl2h
+if ! command -v wsdl2h &> /dev/null; then
+	echo -e "\e[1;41mError: wsdl2h not found, please install gsoap. Try sudo apt-get install gsoap\e[0m"
+	exit
+fi
+echo -e "Executing \e[33mwsdl2h\e[0m"
 wsdl2h -o $tempFolder/wsdl.h $2 2>&1 | grep -i "error"
+
+# soapcpp2
+if ! command -v soapcpp2 &> /dev/null; then
+	echo -e "\e[1;41mError: soapcpp2 not found, please install gsoap. Try sudo apt-get install gsoap\e[0m"
+	exit
+fi
 echo -e "Executing \e[33msoapcpp2\e[0m"
 soapcpp2 -j -CL $tempFolder/wsdl.h -d $tempFolder 2>&1 | grep -i "success\|error"
 
+if [[ ! -f $tempFolder/wsdl.h ]]; then
+	echo -e "\e[1;41mError: $tempFolder/wsdl.h has not been created\e[0m"
+	exit
+fi
+
 classNamespace=$1
+wsdlUrl=$2
 # Read only first occurence found
 readarray -t res <<< $(find $tempFolder -maxdepth 1 -type f -name *.nsmap)
+if [[ ${res[0]} == "" ]]; then
+	echo -e "\e[1;41mError: $tempFolder/wsdl.h has not been created\e[0m"
+	exit
+fi
 serviceNamespace=$(basename ${res[0]} .nsmap)
 wsdlName=$(basename $2 "?wsdl")
 wsdlName=${wsdlName//_/_USCORE}
 
 echo "GSoap generated namespaces:"
+echo -e "wsdlUrl=\e[33m$wsdlUrl\e[0m"
 echo -e "serviceNamespace=\e[33m$serviceNamespace\e[0m"
 echo -e "wsdlName=\e[33m$wsdlName\e[0m"
 echo -e "classNamespace=\e[33m$classNamespace\e[0m"
